version: '2'
services:
  app:
    build: .
    command: npm run start
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      NF_COMMENTS_SERVER_HOST: 0.0.0.0
      NF_COMMENTS_SERVER_PORT: 8080
      NF_COMMENTS_PGHOST: postgres
      NF_COMMENTS_SERVER_MULTINES_HOST: redis
    # Uncomment if you don't want to rebuild the image every time you change the code.
    # A simple restart of the container will pick up the changes
    #
    # volumes:
    #   - .:/usr/app/
    #
  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGPORT: 5432
      PGDATA : /var/lib/postgresql/data/pgdata
    tmpfs:
      - /tmp
      - /var/run/postgresql
      - /var/lib/postgresql/data/pgdata:rw
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
