version: '2'
services:
  app:
    build: .
    command: npm run start
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      NF_COMMENTS_SERVER_HOST: 0.0.0.0
      NF_COMMENTS_SERVER_PORT: 8080
      NF_COMMENTS_PGHOST: postgres
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGPORT: 5432
      PGDATA : /var/lib/postgresql/data/pgdata
    tmpfs:
      - /tmp
      - /var/run/postgresql
      - /var/lib/postgresql/data/pgdata:rw
