export { withResource, withReference, flexibleRender } from './components/core/HOC'
export { Resource } from './components/core/Resource'
export { Notifications, NotificationsContext, NotificationsWrapper } from './components/core/Notifications'
export { HttpService } from './services/HttpService'
export { WebsocketService, buildWebsocketClient } from '././services/WebsocketService'
